version: '2'
services:

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  config-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: boardgamearena/bga-config
    ports:
         - 8888:8888
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  discovery-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: boardgamearena/bga-discovery
    ports:
        - 8081:8081
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
        - config-service
    links:
        - config-service
    entrypoint: ./wait-for-service.sh http://config-service:8888/health

  gateway-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: boardgamearena/bga-gateway
    ports:
      - 8090:8090
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - discovery-service
    links:
      - discovery-service
      - config-service
    entrypoint: ./wait-for-service.sh http://discovery-service:8081/health

  auth-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      API_SERVICE_PASSWORD: $ACCOUNT_SERVICE_PASSWORD
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: boardgamearena/bga-auth
    ports:
      - 8083:8083
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
       - discovery-service
    links:
       - discovery-service
       - config-service
    entrypoint: ./wait-for-service.sh http://discovery-service:8081/health

  auth-mongodb:
    environment:
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: boardgamearena/bga-auth-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - discovery-service
      - auth-service
    links:
      - discovery-service
      - auth-service
      - config-service


  api-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      ACCOUNT_SERVICE_PASSWORD: $ACCOUNT_SERVICE_PASSWORD
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: boardgamearena/bga-api
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
     - discovery-service
     - auth-service
    links:
      - discovery-service
      - auth-service
      - config-service

  api-mongodb:
    environment:
      INIT_DUMP: account-service-dump.js
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: boardgamearena/bga-api-mongodb
    restart: always
    ports:
      - 8082:8082
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - discovery-service
      - auth-service
    links:
      - discovery-service
      - auth-service
      - config-service



