version: '2'
services:

  config-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: boardgamearena/bga-config
     ports:
         - 8888:8888
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  discovery-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: boardgamearena/bga-discovery
    ports:
      - 8761:8761
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
        - config-service
       links:
        - config-service
       entrypoint: ./wait-for-service.sh http://config-service:8888/health

  gateway-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: boardgamearena/bga-gateway
    ports:
      - 80:4000
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - discovery-service
    links:
      - discovery-service
      - config-service
    entrypoint: ./wait-for-service.sh http://discovery-service:8761/health

  auth-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      API_SERVICE_PASSWORD: $ACCOUNT_SERVICE_PASSWORD
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: boardgamearena/auth-service
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
       - discovery-service
    links:
       - discovery-service
       - config-service
     entrypoint: ./wait-for-service.sh http://discovery-service:8761/health

  auth-mongodb:
    environment:
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: boardgamearena/bga-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
     depends_on:
     - discovery-service
     - auth-service
    links:
     - discovery-service
     - auth-service
     - config-service
    entrypoint: ./wait-for-service.sh http://discovery-service:8081/health

  api-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      ACCOUNT_SERVICE_PASSWORD: $ACCOUNT_SERVICE_PASSWORD
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: boardgamearena/bga-api-service
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
 api-service:
    image: spring-ng2-starter/shardis-api
    ports:
     - 8082:8082
    depends_on:
     - discovery-service
     - auth-service
    links:
     - discovery-service
     - auth-service
     - config-service
    entrypoint: ./wait-for-service.sh http://discovery-service:8081/health

  api-mongodb:
    environment:
      INIT_DUMP: account-service-dump.js
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: sqshq/piggymetrics-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
     depends_on:
      - discovery-service
      - auth-service
     links:
      - discovery-service
      - auth-service
      - config-service
     entrypoint: ./wait-for-service.sh http://discovery-service:8081/health


