version: '2'
services:

  config-service:
    image: boardgamearena/bga-config
    ports:
         - 8888:8888
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  discovery-service:
    image: boardgamearena/bga-discovery
    ports:
        - 8081:8081
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
        - config-service
    links:
        - config-service
    entrypoint: ./wait-for-service.sh http://config-service:8888/health

  gateway-service:
    image: boardgamearena/bga-gateway
    ports:
      - 8090:8090
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - discovery-service
    links:
      - discovery-service
      - config-service
    entrypoint: ./wait-for-service.sh http://discovery-service:8081/health

  auth-service:
    environment:
      MONGODB_PASSWORD: odrin7
    image: boardgamearena/bga-auth
    ports:
      - 8083:8083
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
       - discovery-service
    links:
       - discovery-service
       - config-service
    entrypoint: ./wait-for-service.sh http://discovery-service:8081/health

  ui-service:
    image: boardgamearena/bga-ui
    ports:
     - 8080:8080
    depends_on:
     - discovery-service
     - auth-service
     - gateway-service
    links:
     - discovery-service
     - gateway-service
     - auth-service
     - config-service
    entrypoint: ./wait-for-service.sh http://discovery-service:8081/health

  auth-mongodb:
    environment:
      INIT_DUMP: account-service-dump.js
      MONGODB_NAME: boardGameArena
      MONGODB_ROLE: readWrite
      MONGODB_PASSWORD: odrin7
      MONGODB_USER: odrin7
    image: boardgamearena/bga-auth-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

