version: '2'
services:
  message-service:
    build: bga-message
    ports:
      - 8086:8086

  message-mongodb:
    build: bga-mongodb
    ports:
      - 26000:27017

  store-service:
    build: bga-store
    ports:
      - 8087:8087

  store-mongodb:
    build: bga-mongodb
    ports:
      - 27000:27017

  notification-service:
    build: bga-notification
    ports:
      - 8088:8088

  notification-mongodb:
    build: bga-mongodb
    ports:
      - 28000:27017

  statistics-service:
    build: bga-statistics
    ports:
      - 8089:8089

  statistics-mongodb:
    build: bga-mongodb
    ports:
      - 29000:27017





