version: '2'
services:
  message-service:
    build: bga-message
    ports:
      - 8086:8086

  message-mongodb:
    build: bga-mongodb
    ports:
      - 26000:27017

  ui-service:
    build: bga-ui
    ports:
       - 8080:8080

  admin-service:
    build: bga-admin
    ports:
      - 8095:8095
      - 8096:8096
      - 9000:9000
      - 8089:8089

  admin-mongodb:
    build: bga-mongodb
    ports:
      - 29000:27017





