version: '2'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  config-service:
    image: bga/bga-config
    ports:
         - 8888:8888
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  discovery-service:
    image: bga/bga-discovery
    ports:
        - 8081:8081
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
        - config-service
    links:
        - config-service
    entrypoint: ./wait-for-service.sh http://config-service:8888/health

  gateway-service:
    image: bga/bga-gateway
    ports:
      - 8090:8090
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - discovery-service
    links:
      - discovery-service
      - config-service
    entrypoint: ./wait-for-service.sh http://discovery-service:8081/health

  auth-service:
    environment:
      MONGODB_PASSWORD: odrin7
    image: bga/bga-auth
    ports:
      - 8083:8083
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
       - discovery-service
    links:
       - discovery-service
       - config-service
    entrypoint: ./wait-for-service.sh http://discovery-service:8081/health

  auth-mongodb:
    environment:
      INIT_DUMP: nothing.js
      MONGODB_NAME: boardGameArena
      MONGODB_ROLE: readWrite
      MONGODB_PASSWORD: odrin7
      MONGODB_USER: odrin7
    image: bga/bga-auth-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  ui-service:
    image: bga/bga-ui
    ports:
     - 8080:8080
    depends_on:
     - discovery-service
     - auth-service
     - gateway-service
    links:
     - discovery-service
     - gateway-service
     - auth-service
     - config-service
    entrypoint: ./wait-for-service.sh http://discovery-service:8081/health

  api-service:
    environment:
      MONGODB_PASSWORD: odrin7
    image: bga/bga-api
    ports:
      - 8085:8085
    depends_on:
       - discovery-service
       - auth-service
       - api-mongodb
    links:
       - discovery-service
       - auth-service
       - config-service
       - api-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    entrypoint: ./wait-for-service.sh http://discovery-service:8081/health

  api-mongodb:
    environment:
      INIT_DUMP: nothing.js
      MONGODB_NAME: boardGameArena
      MONGODB_ROLE: readWrite
      MONGODB_PASSWORD: odrin7
      MONGODB_USER: odrin7
    image: bga/bga-api-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

