version: '2'
services:

  config-service:
    build: bga-config
    ports:
      - 8888:8888

  discovery-service:
    build: bga-discovery
    ports:
      - 8081:8081

  gateway-service:
    build: bga-gateway

  auth-service:
    build: bga-auth
    ports:
      - 8083:8083

  ui-service:
    build: bga-ui
    ports:
       - 8080:8080


