version: '2'
services:
  config-service:
    image: bga/bga-config
    ports:
         - 8888:8888
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  discovery-service:
    image: bga/bga-discovery
    ports:
        - 8081:8081
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
        - config-service
    links:
        - config-service
    entrypoint: ./wait-for-service.sh http://config-service:8888/health
  gateway-service:
    image: bga/bga-gateway
    ports:
      - 8090:8090
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - discovery-service
    links:
      - discovery-service
      - config-service
    entrypoint: ./wait-for-service.sh http://discovery-service:8081/health

