# EMBEDDED SERVER CONFIGURATION
server:
    port: ${port:8092}

spring:
    aop:
        proxyTargetClass: true
# EUREKA
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true

# EUREKA
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true

---
spring:
  profiles: docker

# EUREKA
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8081/eureka/
---
spring:
  profiles: standalone

# EUREKA
eureka:
  instance:
    hostname: localhost
    port: 8081
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
