# PROFILES
spring:
    application.name: config-service
    profiles.active: @default.spring.profiles@
    aop:
        proxyTargetClass: true
# CONFIGURATION REPO
    cloud:
      config:
        server:
          native:
            search-locations: classpath:/shared

# SERVICE VERSION
info:
    version: @project.version@

# EMBEDDED SERVER CONFIGURATION
server:
    port: ${port:8888}

---

spring:
  profiles: docker


---

spring:
  profiles: standalone


---
security:
  user:
    password: ${CONFIG_SERVICE_PASSWORD}
