# PROFILES
spring:
  application.name: config-service
  profiles.active: @default.spring.profiles@
  aop:
    proxyTargetClass: true
# CONFIGURATION REPO
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
     active: native

# SERVICE VERSION
info:
    version: @project.version@

# EMBEDDED SERVER CONFIGURATION
server:
    port: ${port:8888}
